version = 0.1

[default.deploy.parameters]
stack_name = "job-monitor-stack"
resolve_s3 = true
s3_prefix = "job-monitor-stack"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "TelegramChatId=\"1247822621\""
image_repositories = []

[default.global.parameters]
region = "eu-west-1"
